base_strava: &base_strava
  is_active: true
  handler: strava
  id_config_col: id
  watermark_col: start_date

RAW_STRAVA_ACTIVITIES:
  <<: *base_strava
  description: Ingestion job for raw strava activities data
  publish_mode: APPEND
  extract_method: get_activities
  schedule: 5 2 * * *
  table: strava_activities

RAW_STRAVA_STREAMS:
  <<: *base_strava
  description: Ingestion job for raw strava streams data
  extract_method: get_streams_helper
  extract_params:
    keys:
      - time
      - latlng
      - distance
      - altitude
      - velocity_smooth
      - heartrate
      - cadence
      - watts
      - temp
      - moving
      - grade_smooth
  schedule: 10 2 * * *
  table: strava_streams
